version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    networks:
      - app_network
    extra_hosts:
      - "s.591.com.tw:127.0.0.1"

  redis:
    image: redis:7
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis_data:/data
    networks:
      - app_network
      

volumes:
  redis_data:

networks:
  app_network:
    driver: bridge